spring.application.name=cny-rub-exchange

spring.datasource.url=jdbc:postgresql://localhost:5432/cny_rub_exchange
spring.datasource.username=grigorii
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000